using Raven.CodeAnalysis.CodeGen.Portable;

namespace Raven.CodeAnalysis.NeoClr;

// Adapter-owned admission profile for both declarations and shared bodies.
internal static class NeoClrCapabilities
{
    internal static EmissionCapabilities Shared { get; } = new(
        [EmissionPrimitiveType.NoResult, EmissionPrimitiveType.Int32, EmissionPrimitiveType.Int64, EmissionPrimitiveType.Boolean, EmissionPrimitiveType.String, EmissionPrimitiveType.Byte, EmissionPrimitiveType.Single, EmissionPrimitiveType.Double, EmissionPrimitiveType.SByte, EmissionPrimitiveType.Int16, EmissionPrimitiveType.UInt16, EmissionPrimitiveType.UInt32, EmissionPrimitiveType.UInt64],
        [
            LinearInstructionKind.LoadTypeToken, LinearInstructionKind.BaseConstructorCall, LinearInstructionKind.ConstrainedCall, LinearInstructionKind.EnumFromInt32, LinearInstructionKind.EnumToInt32, LinearInstructionKind.LoadCapture, LinearInstructionKind.UnboxAny, LinearInstructionKind.ReferenceIsNull, LinearInstructionKind.TypeTest, LinearInstructionKind.FieldAddress, LinearInstructionKind.BoxToObject, LinearInstructionKind.ReferenceConvert, LinearInstructionKind.FunctionBind, LinearInstructionKind.FunctionInvoke, LinearInstructionKind.Constant, LinearInstructionKind.Argument, LinearInstructionKind.Add,
            LinearInstructionKind.Subtract, LinearInstructionKind.Multiply, LinearInstructionKind.Call,
            LinearInstructionKind.ConsoleWrite, LinearInstructionKind.String, LinearInstructionKind.Return, LinearInstructionKind.CompilerFailure,
            LinearInstructionKind.LoadLocal, LinearInstructionKind.StoreLocal, LinearInstructionKind.Boolean,
            LinearInstructionKind.Not, LinearInstructionKind.Equal, LinearInstructionKind.Less,
            LinearInstructionKind.Greater, LinearInstructionKind.Label, LinearInstructionKind.Branch,
            LinearInstructionKind.BranchTrue, LinearInstructionKind.BranchFalse, LinearInstructionKind.Pop,
            LinearInstructionKind.ConstantSingle, LinearInstructionKind.ConstantDouble, LinearInstructionKind.ConvertSingle, LinearInstructionKind.ConvertDouble, LinearInstructionKind.LessOrUnordered, LinearInstructionKind.GreaterOrUnordered,
            LinearInstructionKind.ConvertSByte, LinearInstructionKind.ConvertInt16, LinearInstructionKind.ConvertUInt16, LinearInstructionKind.ConvertUInt32, LinearInstructionKind.ConvertUInt64, LinearInstructionKind.UnsignedDivide, LinearInstructionKind.UnsignedRemainder, LinearInstructionKind.UnsignedShiftRight, LinearInstructionKind.UnsignedLess, LinearInstructionKind.UnsignedGreater, LinearInstructionKind.UnsignedConvertDouble,
            LinearInstructionKind.Constant64, LinearInstructionKind.Convert64, LinearInstructionKind.Convert32, LinearInstructionKind.ConvertByte,
            LinearInstructionKind.Negate, LinearInstructionKind.Complement, LinearInstructionKind.Divide, LinearInstructionKind.Remainder,
            LinearInstructionKind.BitwiseAnd, LinearInstructionKind.BitwiseOr, LinearInstructionKind.BitwiseXor,
            LinearInstructionKind.ShiftLeft, LinearInstructionKind.ShiftRight, LinearInstructionKind.Receiver, LinearInstructionKind.LoadField, LinearInstructionKind.StoreField, LinearInstructionKind.ValueInstanceCall, LinearInstructionKind.InstanceCall, LinearInstructionKind.InterfaceCall, LinearInstructionKind.NewObject,
            LinearInstructionKind.NewArray, LinearInstructionKind.LoadElement, LinearInstructionKind.StoreElement, LinearInstructionKind.ArrayLength, LinearInstructionKind.LocalAddress, LinearInstructionKind.ArgumentAddress, LinearInstructionKind.LoadIndirect, LinearInstructionKind.StoreIndirect, LinearInstructionKind.DefaultValue, LinearInstructionKind.Duplicate
        ],
        [EmissionDeclarationKind.StaticInterfaceMethod, EmissionDeclarationKind.Enum, EmissionDeclarationKind.AssemblyFunction, EmissionDeclarationKind.NamespacedAssemblyFunction, EmissionDeclarationKind.StaticMethod, EmissionDeclarationKind.StaticType, EmissionDeclarationKind.RootClass, EmissionDeclarationKind.ValueType, EmissionDeclarationKind.ValueInterfaceImplementation, EmissionDeclarationKind.ValueObjectOverride, EmissionDeclarationKind.NestedType, EmissionDeclarationKind.InstanceMethod, EmissionDeclarationKind.Constructor, EmissionDeclarationKind.PropertyAccessor, EmissionDeclarationKind.IndexerAccessor, EmissionDeclarationKind.Interface, EmissionDeclarationKind.InterfaceMethod, EmissionDeclarationKind.InterfaceProperty, EmissionDeclarationKind.InterfaceIndexer, EmissionDeclarationKind.InterfaceInheritance, EmissionDeclarationKind.InterfaceImplementation],
        [Accessibility.Public, Accessibility.Internal],
        [Accessibility.Public, Accessibility.Internal, Accessibility.Private],
        [Accessibility.Public, Accessibility.Internal], allowsRootClassLocals: true, allowsRootClassSignatures: true, allowsArrays: true, allowsGenericMethods: true, allowsGenericInstanceMethods: true, allowsGenericStaticOwners: true, allowsGenericClassOwners: true, allowsConstructedFieldReferences: true, allowsNominalTypeBounds: true, allowsSpecialTypeConstraints: true, allowsGenericInterfaceDeclarations: true, allowsExternalInterfaceDeclarations: true, allowsConstructedInterfaceInheritance: true, allowsConstructedInterfaceImplementations: true, allowsInterfaceSignatures: true, allowsInterfaceDispatch: true, allowsExternalReferenceSignatures: true, allowsExternalValueSignatures: true, allowsExternalInstanceCalls: true, allowsManagedReferences: true, allowsExternalValueInstanceCalls: true, allowsExternalConstructors: true, allowsNestedExternalTypes: true, allowsFunctionValues: true, allowsLoweredExtensionCalls: true, allowsCasePatterns: true, allowsReferenceEnumeration: true, allowsObjectDisplayDispatch: true, allowsObjectHashDispatch: true, allowsRangeEnumeration: true, allowsMethodInterfaceBounds: true, allowsLocalClassInheritance: true, allowsClosedClassFamilies: true, allowsProtectedConstructors: true, allowsClosedInterfaceFamilies: true);
}
