using Raven.CodeAnalysis.Semantics.Tests;

namespace Raven.CodeAnalysis.Tests.Documentation;

public sealed class RavenDocGenerationTests : CompilationTestBase
{
    [Fact]
    public void SourceCompilation_GeneratesRavenApiSite()
    {
        var (compilation, _) = CreateCompilation("""
            namespace Samples.Docs

            /// A documented Raven type from version {{ productVersion }}.
            /// Published at [the API root]({{apiRoot}}).
            /// The unresolved {{futureValue}} remains visible.
            ///
            /// ## Usage
            ///
            /// Call [GetTitle](xref:M:Samples.Docs.Widget.GetTitle).
            ///
            /// ```raven
            /// let widget = Widget()
            /// ```
            public class Widget {
                /// Returns the current title.
                public func GetTitle() -> string => "Raven"

                /// Returns the supplied reference.
                /// @typeparam T The reference type to preserve.
                public func Echo<T>(value: T) -> T where T: class => value

                val PublicInit: string { init; }
                val PrivateSet: string { private set; }
                val ProtectedSet: string { protected set; }
            }
            """, assemblyName: "RavenDoc.Sample");
        var outputPath = Path.Combine(
            Path.GetTempPath(),
            "ravendoc-tests",
            Guid.NewGuid().ToString("N"));
        var siteRootPath = Path.GetDirectoryName(outputPath)!;

        try
        {
            DocumentationGenerator.ProcessCompilation(
                compilation,
                outputPath,
                new DocumentationSiteOptions(
                    [
                        new DocumentationSiteLink(
                            "Raven documentation",
                            "https://example.com/raven/")
                    ],
                    new Dictionary<string, string>
                    {
                        ["productVersion"] = "1.2.3+build.7",
                        ["apiRoot"] = "../reference/"
                    },
                    siteRootPath));

            var typePagePath = Path.Combine(outputPath, "Samples", "Docs", "Widget", "index.html");
            var memberPagePath = Path.Combine(outputPath, "Samples", "Docs", "Widget", "method_GetTitle.html");
            var genericMemberPagePath = Path.Combine(outputPath, "Samples", "Docs", "Widget", "method_Echo.html");

            File.Exists(typePagePath).ShouldBeTrue();
            File.Exists(memberPagePath).ShouldBeTrue();
            File.Exists(genericMemberPagePath).ShouldBeTrue();

            var typePage = File.ReadAllText(typePagePath);
            typePage.ShouldContain("Raven API reference");
            typePage.ShouldContain("href=\"../../../../index.html\"");
            typePage.ShouldContain("api-hero");
            typePage.ShouldContain("member-card");
            typePage.ShouldContain("symbol-icon--function");
            typePage.ShouldContain("id=\"methods\"");
            typePage.ShouldContain("A documented Raven type from version 1.2.3+build.7.");
            typePage.ShouldContain("href=\"../reference/\"");
            typePage.ShouldContain("The unresolved {{futureValue}} remains visible.");
            typePage.ShouldNotContain("{{ productVersion }}");
            typePage.ShouldContain("method_GetTitle.html");
            typePage.ShouldContain("language-raven");
            typePage.ShouldContain("class Widget");
            typePage.ShouldNotContain("public class Widget");
            typePage.ShouldContain("val PublicInit: string { init; }");
            typePage.ShouldContain("val PrivateSet: string");
            typePage.ShouldNotContain("private set;");
            typePage.ShouldContain("val ProtectedSet: string { protected set; }");
            typePage.ShouldContain("site.js");
            typePage.ShouldContain("raven-theme.css");
            typePage.ShouldContain("Generated by RavenDoc");
            typePage.ShouldContain("Raven documentation");
            typePage.ShouldContain("https://example.com/raven/");
            typePage.ShouldNotContain("System/Object/index.html");
            typePage.Split(">Usage</h2>", StringSplitOptions.None).Length.ShouldBe(2);

            var memberPage = File.ReadAllText(memberPagePath);
            memberPage.ShouldContain("func GetTitle() -&gt; string");
            memberPage.ShouldContain("Returns the current title.");
            var genericMemberPage = File.ReadAllText(genericMemberPagePath);
            genericMemberPage.ShouldContain("func Echo&lt;T&gt;(value: T) -&gt; T where T: class");
            genericMemberPage.ShouldContain("Returns the supplied reference.");
            genericMemberPage.ShouldContain("Type parameters");
            genericMemberPage.ShouldContain("The reference type to preserve.");
            genericMemberPage.ShouldNotContain("@typeparam");
            File.ReadAllText(Path.Combine(outputPath, "site.js"))
                .ShouldContain("ravenKeywords");
            var sharedTheme = File.ReadAllText(Path.Combine(outputPath, "raven-theme.css"));
            sharedTheme.ShouldContain("--raven-accent");
            sharedTheme.ShouldContain("--raven-syntax-keyword: #569cd6");
            sharedTheme.ShouldContain("--raven-code-bg: #1e1e1e");
            File.ReadAllText(Path.Combine(outputPath, "style.css"))
                .ShouldContain("color: var(--raven-syntax-keyword)");
        }
        finally
        {
            if (Directory.Exists(outputPath))
                Directory.Delete(outputPath, recursive: true);
        }
    }

    [Fact]
    public void Macro_GeneratesNamespaceMemberPage()
    {
        var (compilation, _) = CreateCompilation("""
            namespace Samples.Macros

            /// Quotes a Raven expression.
            ///
            /// See the [syntax-tree API](https://example.com/syntax-tree).
            public macro Quote() { }

            /// Returns a greeting from the namespace.
            public func Greet() -> string => "Hello"
            """, assemblyName: "RavenDoc.Macros");
        var outputPath = Path.Combine(
            Path.GetTempPath(),
            "ravendoc-tests",
            Guid.NewGuid().ToString("N"));

        try
        {
            DocumentationGenerator.ProcessCompilation(compilation, outputPath);

            var namespacePagePath = Path.Combine(
                outputPath,
                "Samples",
                "Macros",
                "index.html");
            var macroPagePath = Path.Combine(
                outputPath,
                "Samples",
                "Macros",
                "macro_Quote.html");
            var functionPagePath = Path.Combine(
                outputPath,
                "Samples",
                "Macros",
                "method_Greet.html");

            File.Exists(namespacePagePath).ShouldBeTrue();
            File.Exists(macroPagePath).ShouldBeTrue();
            File.Exists(functionPagePath).ShouldBeTrue();

            var namespacePage = File.ReadAllText(namespacePagePath);
            namespacePage.ShouldContain("Macros");
            namespacePage.ShouldContain("macro_Quote.html");
            namespacePage.ShouldContain("Functions");
            namespacePage.ShouldContain("method_Greet.html");

            var macroPage = File.ReadAllText(macroPagePath);
            macroPage.ShouldContain("Quotes a Raven expression.");
            macroPage.ShouldContain("https://example.com/syntax-tree");
            macroPage.ShouldContain("RavenDoc.Macros.dll");
            macroPage.ShouldContain("Samples.Macros");

            var functionPage = File.ReadAllText(functionPagePath);
            functionPage.ShouldContain("Returns a greeting from the namespace.");
            functionPage.ShouldContain("CLR container (for .NET interop)");
        }
        finally
        {
            if (Directory.Exists(outputPath))
                Directory.Delete(outputPath, recursive: true);
        }
    }

    [Fact]
    public void MetadataExtension_HidesCompilerGeneratedGroupingTypes()
    {
        var metadataReference = TestMetadataFactory.CreateFileReferenceFromSource(
            """
            namespace Samples.Extensions

            public extension TextExtensions for string {
                func WordCount() -> int { 0 }
            }
            """,
            assemblyName: $"RavenDoc.Extensions.{Guid.NewGuid():N}");
        var hostCompilation = Compilation.Create(
                "RavenDoc.MetadataHost",
                options: new CompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .AddReferences(TestMetadataReferences.Default)
            .AddReferences(metadataReference);
        _ = hostCompilation.GetDiagnostics();
        var assembly = Assert.IsAssignableFrom<IAssemblySymbol>(
            hostCompilation.GetAssemblyOrModuleSymbol(metadataReference));
        var outputPath = Path.Combine(
            Path.GetTempPath(),
            "ravendoc-tests",
            Guid.NewGuid().ToString("N"));

        try
        {
            DocumentationGenerator.ProcessAssembly(hostCompilation, assembly, outputPath);

            var extensionPagePath = Path.Combine(
                outputPath,
                "Samples",
                "Extensions",
                "TextExtensions",
                "index.html");
            File.Exists(extensionPagePath).ShouldBeTrue();

            var extensionPage = File.ReadAllText(extensionPagePath);
            extensionPage.ShouldNotContain("<>__RavenExtensionGrouping");
            extensionPage.ShouldNotContain("<>__RavenExtensionMarker");

            Directory.EnumerateFileSystemEntries(outputPath, "*", SearchOption.AllDirectories)
                .ShouldNotContain(path =>
                    path.Contains("<>__RavenExtensionGrouping", StringComparison.Ordinal) ||
                    path.Contains("<>__RavenExtensionMarker", StringComparison.Ordinal));
        }
        finally
        {
            if (Directory.Exists(outputPath))
                Directory.Delete(outputPath, recursive: true);
        }
    }

    [Fact]
    public void CaseDeclaredUnion_GroupsProjectedCasesUnderUnion()
    {
        var (compilation, _) = CreateCompilation("""
            namespace Samples.Unions

            /// A result with named cases.
            public union Outcome<T, E> {
                /// Contains a successful value.
                case Success(value: T)

                /// Contains an error value.
                case Failure(error: E)
            }

            /// A union of member types without named cases.
            public union Scalar(int | string)
            """, assemblyName: "RavenDoc.Unions");
        var outputPath = Path.Combine(
            Path.GetTempPath(),
            "ravendoc-tests",
            Guid.NewGuid().ToString("N"));

        try
        {
            DocumentationGenerator.ProcessCompilation(compilation, outputPath);

            var outcomePagePath = Path.Combine(
                outputPath,
                "Samples",
                "Unions",
                "Outcome`2",
                "index.html");
            var scalarPagePath = Path.Combine(
                outputPath,
                "Samples",
                "Unions",
                "Scalar",
                "index.html");

            var outcomePage = File.ReadAllText(outcomePagePath);
            outcomePage.ShouldContain("id=\"cases\"");
            outcomePage.ShouldContain("case Success(value: T)");
            outcomePage.ShouldContain("Contains a successful value.");
            outcomePage.ShouldContain("case Failure(error: E)");
            outcomePage.ShouldContain("Contains an error value.");
            outcomePage.ShouldNotContain("Outcome_Success");
            outcomePage.ShouldNotContain("Outcome_Failure");

            var scalarPage = File.ReadAllText(scalarPagePath);
            scalarPage.ShouldNotContain("id=\"cases\"");
            scalarPage.ShouldNotContain(">Cases<");

            Directory.EnumerateFileSystemEntries(outputPath, "*", SearchOption.AllDirectories)
                .ShouldNotContain(path =>
                    path.Contains("Outcome_Success", StringComparison.Ordinal) ||
                    path.Contains("Outcome_Failure", StringComparison.Ordinal));
        }
        finally
        {
            if (Directory.Exists(outputPath))
                Directory.Delete(outputPath, recursive: true);
        }
    }

    [Fact]
    public void MetadataUnion_ProjectsLogicalCaseNamesOnUnionPage()
    {
        var metadataReference = TestMetadataFactory.CreateFileReferenceFromSource(
            """
            namespace Samples.MetadataUnions

            public union Outcome<T, E> {
                case Success(value: T)
                case Failure(error: E)
            }
            """,
            assemblyName: $"RavenDoc.MetadataUnions.{Guid.NewGuid():N}");
        var hostCompilation = Compilation.Create(
                "RavenDoc.MetadataHost",
                options: new CompilationOptions(OutputKind.DynamicallyLinkedLibrary))
            .AddReferences(TestMetadataReferences.Default)
            .AddReferences(metadataReference);
        _ = hostCompilation.GetDiagnostics();
        var assembly = Assert.IsAssignableFrom<IAssemblySymbol>(
            hostCompilation.GetAssemblyOrModuleSymbol(metadataReference));
        var outputPath = Path.Combine(
            Path.GetTempPath(),
            "ravendoc-tests",
            Guid.NewGuid().ToString("N"));

        try
        {
            DocumentationGenerator.ProcessAssembly(hostCompilation, assembly, outputPath);

            var outcomePage = File.ReadAllText(Path.Combine(
                outputPath,
                "Samples",
                "MetadataUnions",
                "Outcome`2",
                "index.html"));
            outcomePage.ShouldContain("id=\"cases\"");
            outcomePage.ShouldContain("case Success(value: T)");
            outcomePage.ShouldContain("case Failure(error: E)");
            outcomePage.ShouldNotContain("Outcome_Success");
            outcomePage.ShouldNotContain("Outcome_Failure");

            var namespacePage = File.ReadAllText(Path.Combine(
                outputPath,
                "Samples",
                "MetadataUnions",
                "index.html"));
            namespacePage.ShouldNotContain("Outcome_Success");
            namespacePage.ShouldNotContain("Outcome_Failure");

            Directory.EnumerateFileSystemEntries(outputPath, "*", SearchOption.AllDirectories)
                .ShouldNotContain(path =>
                    path.Contains("Outcome_Success", StringComparison.Ordinal) ||
                    path.Contains("Outcome_Failure", StringComparison.Ordinal));
        }
        finally
        {
            if (Directory.Exists(outputPath))
                Directory.Delete(outputPath, recursive: true);
        }
    }
}
