using Raven.CodeAnalysis.Semantics.Tests;

namespace Raven.CodeAnalysis.Tests.Documentation;

public sealed class RavenDocGenerationTests : CompilationTestBase
{
    [Fact]
    public void SourceCompilation_GeneratesRavenApiSite()
    {
        var (compilation, _) = CreateCompilation("""
            namespace Samples.Docs

            /// A documented Raven type.
            ///
            /// ## Usage
            ///
            /// Call [GetTitle](xref:M:Samples.Docs.Widget.GetTitle).
            ///
            /// ```raven
            /// let widget = Widget()
            /// ```
            public class Widget {
                /// Returns the current title.
                public func GetTitle() -> string => "Raven"
            }
            """, assemblyName: "RavenDoc.Sample");
        var outputPath = Path.Combine(
            Path.GetTempPath(),
            "ravendoc-tests",
            Guid.NewGuid().ToString("N"));

        try
        {
            DocumentationGenerator.ProcessCompilation(compilation, outputPath);

            var typePagePath = Path.Combine(outputPath, "Samples", "Docs", "Widget", "index.html");
            var memberPagePath = Path.Combine(outputPath, "Samples", "Docs", "Widget", "method_GetTitle.html");

            File.Exists(typePagePath).ShouldBeTrue();
            File.Exists(memberPagePath).ShouldBeTrue();

            var typePage = File.ReadAllText(typePagePath);
            typePage.ShouldContain("Raven API reference");
            typePage.ShouldContain("A documented Raven type.");
            typePage.ShouldContain("method_GetTitle.html");
            typePage.ShouldContain("language-raven");
            typePage.ShouldContain("highlight.js");
            typePage.ShouldContain("raven-theme.css");
            typePage.ShouldContain("Generated by RavenDoc");
            typePage.ShouldNotContain("System/Object/index.html");

            var memberPage = File.ReadAllText(memberPagePath);
            memberPage.ShouldContain("GetTitle() → string");
            memberPage.ShouldContain("Returns the current title.");
            File.ReadAllText(Path.Combine(outputPath, "highlight.js"))
                .ShouldContain("ravenKeywords");
            File.ReadAllText(Path.Combine(outputPath, "raven-theme.css"))
                .ShouldContain("--raven-accent");
        }
        finally
        {
            if (Directory.Exists(outputPath))
                Directory.Delete(outputPath, recursive: true);
        }
    }
}
