<Project>
  <PropertyGroup Condition="'$(MSBuildProjectExtension)' == '.rvnproj' and '$(LanguageTargets)' == ''">
    <LanguageTargets>$(MSBuildThisFileDirectory)build/Raven.Language.targets</LanguageTargets>
    <DefaultLanguageSourceExtension>.rvn</DefaultLanguageSourceExtension>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' != 'Release'">
    <DefineConstants>$(DefineConstants);RAVEN_INSTRUMENTATION</DefineConstants>
  </PropertyGroup>
</Project>
