using System.Text;

namespace BoundNodeGenerator;

static class SymbolPartialGenerator
{
    public static string Generate(SymbolClassModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("using Raven.CodeAnalysis;");
        builder.AppendLine();
        builder.AppendLine($"namespace {model.Namespace};");
        builder.AppendLine();
        builder.AppendLine($"{model.Accessibility} partial class {model.Name}");
        builder.AppendLine("{");
        var visitName = model.VisitorMethodName;
        builder.AppendLine("    public override void Accept(SymbolVisitor visitor)");
        builder.AppendLine("    {");
        builder.AppendLine($"        visitor.Visit{visitName}(this);");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public override TResult Accept<TResult>(SymbolVisitor<TResult> visitor)");
        builder.AppendLine("    {");
        builder.AppendLine($"        return visitor.Visit{visitName}(this);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }
}
