using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;

var repoRoot = Path.GetFullPath(Path.Combine(AppContext.BaseDirectory, "..", "..", "..", "..", ".."));
var kindFile = Path.Combine(repoRoot, "src", "Raven.CodeAnalysis", "Operations", "OperationKind.cs");
var kinds = ParseKinds(kindFile);

var typeMap = new Dictionary<string, string>(StringComparer.Ordinal)
{
    ["Block"] = "BlockOperation",
    ["BlockExpression"] = "BlockOperation",
    ["ExpressionStatement"] = "ExpressionStatementOperation",
    ["LocalDeclaration"] = "VariableDeclarationOperation",
    ["Function"] = "FunctionOperation",
    ["VariableDeclarator"] = "VariableDeclaratorOperation",
    ["Return"] = "ReturnOperation",
    ["Throw"] = "ThrowOperation",
    ["Break"] = "BreakOperation",
    ["Continue"] = "ContinueOperation",
    ["Goto"] = "GotoOperation",
    ["Labeled"] = "LabeledOperation",
    ["Try"] = "TryOperation",
    ["CatchClause"] = "CatchClauseOperation",
    ["Literal"] = "LiteralOperation",
    ["DefaultValue"] = "DefaultValueOperation",
    ["LocalReference"] = "LocalReferenceOperation",
    ["ParameterReference"] = "ParameterReferenceOperation",
    ["FieldReference"] = "FieldReferenceOperation",
    ["PropertyReference"] = "PropertyReferenceOperation",
    ["MethodReference"] = "MethodReferenceOperation",
    ["Unary"] = "UnaryOperation",
    ["Binary"] = "BinaryOperation",
    ["Parenthesized"] = "ParenthesizedOperation",
    ["Conversion"] = "ConversionOperation",
    ["Conditional"] = "ConditionalOperation",
    ["ConditionalAccess"] = "ConditionalAccessOperation",
    ["TryExpression"] = "TryExpressionOperation",
    ["WhileLoop"] = "WhileOperation",
    ["ForLoop"] = "ForOperation",
    ["Invocation"] = "InvocationOperation",
    ["ObjectCreation"] = "ObjectCreationOperation",
    ["Assignment"] = "AssignmentOperation",
    ["DelegateCreation"] = "DelegateCreationOperation",
    ["Tuple"] = "TupleOperation",
    ["AddressOf"] = "AddressOfOperation",
    ["ArrayElement"] = "ElementAccessOperation",
    ["IndexerElement"] = "ElementAccessOperation",
    ["TypeOf"] = "TypeOfOperation",
    ["Lambda"] = "LambdaOperation",
    ["Switch"] = "SwitchOperation",
    ["Collection"] = "CollectionOperation",
    ["TypeExpression"] = "TypeOperation",
    ["NamespaceExpression"] = "NamespaceOperation",
    ["SelfReference"] = "SelfOperation",
    ["Unit"] = "UnitOperation",
    ["Invalid"] = "InvalidOperation",
};

var outputDir = Path.Combine(repoRoot, "src", "Raven.CodeAnalysis", "Operations", "generated");
Directory.CreateDirectory(outputDir);

File.WriteAllText(Path.Combine(outputDir, "OperationVisitor.g.cs"), GenerateVisitors(kinds, typeMap));
File.WriteAllText(Path.Combine(outputDir, "OperationRewriter.g.cs"), GenerateRewriter(kinds, typeMap));
File.WriteAllText(Path.Combine(outputDir, "OperationWalker.g.cs"), GenerateWalker(kinds, typeMap));

static ImmutableArray<string> ParseKinds(string filePath)
{
    var builder = ImmutableArray.CreateBuilder<string>();
    var regex = new Regex("^(?<name>[A-Za-z0-9_]+)\\s*,", RegexOptions.Compiled);

    foreach (var line in File.ReadAllLines(filePath))
    {
        var trimmed = line.Trim();
        if (trimmed.StartsWith("/", StringComparison.Ordinal))
            continue;

        var match = regex.Match(trimmed);
        if (!match.Success)
            continue;

        var name = match.Groups["name"].Value;
        if (name is "None")
            continue;

        builder.Add(name);
    }

    return builder.ToImmutable();
}

static string GenerateVisitors(ImmutableArray<string> kinds, IReadOnlyDictionary<string, string> typeMap)
{
    var builder = new StringBuilder();
    builder.AppendLine("// <auto-generated />");
    builder.AppendLine("#nullable enable");
    builder.AppendLine();
    builder.AppendLine("namespace Raven.CodeAnalysis.Operations;");
    builder.AppendLine();
    builder.AppendLine("public partial class OperationVisitor");
    builder.AppendLine("{");

    foreach (var kind in kinds)
    {
        if (!typeMap.TryGetValue(kind, out var typeName))
            continue;

        builder.AppendLine($"    public virtual void Visit{kind}({typeName} operation) => DefaultVisit(operation);");
    }

    builder.AppendLine("}");
    builder.AppendLine();
    builder.AppendLine("public partial class OperationVisitor<TResult>");
    builder.AppendLine("{");

    foreach (var kind in kinds)
    {
        if (!typeMap.TryGetValue(kind, out var typeName))
            continue;

        builder.AppendLine($"    public virtual TResult Visit{kind}({typeName} operation) => DefaultVisit(operation);");
    }

    builder.AppendLine("}");
    return builder.ToString();
}

static string GenerateRewriter(ImmutableArray<string> kinds, IReadOnlyDictionary<string, string> typeMap)
{
    var builder = new StringBuilder();
    builder.AppendLine("// <auto-generated />");
    builder.AppendLine("#nullable enable");
    builder.AppendLine();
    builder.AppendLine("namespace Raven.CodeAnalysis.Operations;");
    builder.AppendLine();
    builder.AppendLine("internal partial class OperationRewriter : OperationVisitor<IOperation?>");
    builder.AppendLine("{");
    builder.AppendLine("    public override IOperation? Visit(IOperation operation)");
    builder.AppendLine("    {");
    builder.AppendLine("        return operation switch");
    builder.AppendLine("        {");

    var seenTypes = new HashSet<string>(StringComparer.Ordinal);

    foreach (var kind in kinds)
    {
        if (!typeMap.TryGetValue(kind, out var typeName))
            continue;

        if (!seenTypes.Add(typeName))
            continue;

        builder.AppendLine($"            {typeName} op => Visit{kind}(op),");
    }

    builder.AppendLine("            _ => base.Visit(operation),");
    builder.AppendLine("        };\n    }");
    builder.AppendLine();

    foreach (var kind in kinds)
    {
        if (!typeMap.TryGetValue(kind, out var typeName))
            continue;

        builder.AppendLine($"    public virtual IOperation? Visit{kind}({typeName} operation) => DefaultVisit(operation);");
    }

    builder.AppendLine("}");
    return builder.ToString();
}

static string GenerateWalker(ImmutableArray<string> kinds, IReadOnlyDictionary<string, string> typeMap)
{
    var builder = new StringBuilder();
    builder.AppendLine("// <auto-generated />");
    builder.AppendLine("#nullable enable");
    builder.AppendLine();
    builder.AppendLine("namespace Raven.CodeAnalysis.Operations;");
    builder.AppendLine();
    builder.AppendLine("public partial class OperationWalker : OperationVisitor");
    builder.AppendLine("{");
    builder.AppendLine("    public override void Visit(IOperation operation)");
    builder.AppendLine("    {");
    builder.AppendLine("        switch (operation)");
    builder.AppendLine("        {");

    var seenTypes = new HashSet<string>(StringComparer.Ordinal);

    foreach (var kind in kinds)
    {
        if (!typeMap.TryGetValue(kind, out var typeName))
            continue;

        if (!seenTypes.Add(typeName))
            continue;

        builder.AppendLine($"            case {typeName} op:");
        builder.AppendLine($"                Visit{kind}(op);");
        builder.AppendLine("                break;");
    }

    builder.AppendLine("            default:");
    builder.AppendLine("                base.Visit(operation);");
    builder.AppendLine("                break;");
    builder.AppendLine("        }\n    }");
    builder.AppendLine("}");
    return builder.ToString();
}
