using System.Text;

internal sealed class RavenDocSiteTemplate
{
    private const string StyleResourceName = "RavenDoc.Style.css";
    private const string ScriptResourceName = "RavenDoc.Site.js";
    private const string ThemeResourceName = "Raven.Theme.css";

    public void WriteAssets(string outputDirectory)
    {
        WriteResource(outputDirectory, ThemeResourceName, "raven-theme.css");
        WriteResource(outputDirectory, StyleResourceName, "style.css");
        WriteResource(outputDirectory, ScriptResourceName, "site.js");
    }

    public string RenderPage(RavenDocPageTemplateModel page)
    {
        var title = $"{page.Title} · {page.AssemblyName}";
        var siteNavigation = page.SiteLinks.Count == 0
            ? string.Empty
            : $"""
              <nav class="site-navigation" aria-label="Related documentation">
                {string.Join(
                    Environment.NewLine,
                    page.SiteLinks.Select(link =>
                        $"<a href=\"{Escape(link.Url)}\">{Escape(link.Label)}</a>"))}
              </nav>
              """;

        return $"""
        <!doctype html>
        <html lang="en">
        <head>
          <meta charset="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <title>{Escape(title)}</title>
          <link rel="stylesheet" href="{Escape(page.ThemeHref)}" />
          <link rel="stylesheet" href="{Escape(page.StyleHref)}" />
          <script defer src="{Escape(page.ScriptHref)}"></script>
        </head>
        <body>
          <header class="site-header">
            <a class="raven-brand" href="{Escape(page.HomeHref)}">
              <span class="raven-brand-mark">R</span>
              <span class="raven-brand-copy">
                <strong>{Escape(page.AssemblyName)}</strong>
                <small>Raven API reference</small>
              </span>
            </a>
            {siteNavigation}
            <span class="page-context">{Escape(page.Context)}</span>
          </header>
          <div class="documentation-shell">
            <main class="content-shell">
              <article class="api-content">
                {page.BodyHtml}
              </article>
            </main>
            <aside class="page-outline" aria-label="On this page">
              <div class="page-outline-card">
                <strong>On this page</strong>
                <nav id="page-outline-links"></nav>
              </div>
            </aside>
          </div>
          <footer>Generated by RavenDoc</footer>
        </body>
        </html>
        """;
    }

    public string RenderHero(RavenDocSymbolKind kind, string kindLabel, string title, string? signature)
    {
        var signatureHtml = string.IsNullOrWhiteSpace(signature)
            ? string.Empty
            : $"""
              <pre class="api-signature"><code class="language-raven">{Escape(signature)}</code></pre>
              """;

        return $"""
        <header class="api-hero">
          <div class="api-kind">
            {RenderIcon(kind)}
            <span>{Escape(kindLabel)}</span>
          </div>
          <h1>{Escape(title)}</h1>
          {signatureHtml}
        </header>
        """;
    }

    public string RenderMemberSection(
        string title,
        IReadOnlyList<RavenDocMemberTemplateModel> members)
    {
        var rows = new StringBuilder();
        foreach (var member in members)
        {
            var summary = string.IsNullOrWhiteSpace(member.Summary)
                ? "<span class=\"member-summary member-summary--empty\">No summary available.</span>"
                : $"<span class=\"member-summary\">{Escape(member.Summary)}</span>";

            rows.AppendLine($"""
              <a class="member-card" href="{Escape(member.Href)}">
                {RenderIcon(member.Kind)}
                <span class="member-card-content">
                  <span class="member-signature">{Escape(member.Signature)}</span>
                  {summary}
                </span>
                <span class="member-arrow" aria-hidden="true">→</span>
              </a>
            """);
        }

        return $"""
        <section class="member-section" aria-labelledby="{GetHeadingId(title)}">
          <div class="section-heading">
            <h2 id="{GetHeadingId(title)}">{Escape(title)}</h2>
            <span>{members.Count} {Pluralize(members.Count, "item", "items")}</span>
          </div>
          <div class="member-list">
            {rows}
          </div>
        </section>
        """;
    }

    public string RenderCaseSection(
        IReadOnlyList<RavenDocCaseTemplateModel> cases)
    {
        var rows = new StringBuilder();
        foreach (var @case in cases)
        {
            var summary = string.IsNullOrWhiteSpace(@case.Summary)
                ? "<span class=\"member-summary member-summary--empty\">No summary available.</span>"
                : $"<span class=\"member-summary\">{Escape(@case.Summary)}</span>";

            rows.AppendLine($"""
              <div class="member-card member-card--static">
                {RenderIcon(RavenDocSymbolKind.Case)}
                <span class="member-card-content">
                  <span class="member-signature">{Escape(@case.Signature)}</span>
                  {summary}
                </span>
              </div>
            """);
        }

        return $"""
        <section class="member-section" aria-labelledby="cases">
          <div class="section-heading">
            <h2 id="cases">Cases</h2>
            <span>{cases.Count} {Pluralize(cases.Count, "case", "cases")}</span>
          </div>
          <div class="member-list">
            {rows}
          </div>
        </section>
        """;
    }

    public string RenderSignature(string signature)
        => $"""
           <pre class="api-signature api-signature--variant"><code class="language-raven">{Escape(signature)}</code></pre>
           """;

    private static string RenderIcon(RavenDocSymbolKind kind)
    {
        var (label, paths) = kind switch
        {
            RavenDocSymbolKind.Namespace => ("Namespace", """
                <path d="M4 5.5h6l1.5 2H20v11H4z" />
                <path d="M4 9h16" />
                """),
            RavenDocSymbolKind.Type => ("Type", """
                <path d="M5 4h14v16H5z" />
                <path d="M9 8h6M12 8v8" />
                """),
            RavenDocSymbolKind.Function => ("Function", """
                <path d="M8 19c2-5 2-9 4-13 1-2 3-2 4 0" />
                <path d="M6 11h9" />
                """),
            RavenDocSymbolKind.Macro => ("Macro", """
                <path d="m12 3 1.4 5.6L19 10l-5.6 1.4L12 17l-1.4-5.6L5 10l5.6-1.4z" />
                <path d="m18 16 .6 2.4L21 19l-2.4.6L18 22l-.6-2.4L15 19l2.4-.6z" />
                """),
            RavenDocSymbolKind.Case => ("Case", """
                <circle cx="7" cy="7" r="2" />
                <circle cx="17" cy="17" r="2" />
                <path d="M9 7h2a6 6 0 0 1 6 6v2" />
                """),
            RavenDocSymbolKind.Property => ("Property", """
                <path d="M6 5h12v14H6z" />
                <path d="M9 9h6M9 13h4" />
                """),
            RavenDocSymbolKind.Field => ("Field", """
                <circle cx="12" cy="12" r="7" />
                <path d="M9 12h6" />
                """),
            RavenDocSymbolKind.Event => ("Event", """
                <path d="M12 3v5M12 16v5M3 12h5M16 12h5" />
                <circle cx="12" cy="12" r="4" />
                """),
            RavenDocSymbolKind.Operator => ("Operator", """
                <path d="M5 8h14M5 16h14M9 5v6M15 13v6" />
                """),
            _ => ("Member", """
                <circle cx="12" cy="12" r="7" />
                <path d="M12 9v6M9 12h6" />
                """)
        };

        return $"""
               <span class="symbol-icon symbol-icon--{kind.ToString().ToLowerInvariant()}" title="{label}" aria-hidden="true">
                 <svg viewBox="0 0 24 24" focusable="false">{paths}</svg>
               </span>
               """;
    }

    private static string Pluralize(int count, string singular, string plural)
        => count == 1 ? singular : plural;

    private static string GetHeadingId(string title)
    {
        var builder = new StringBuilder(title.Length);
        var needsSeparator = false;
        foreach (var character in title)
        {
            if (char.IsLetterOrDigit(character))
            {
                if (needsSeparator && builder.Length > 0)
                    builder.Append('-');
                builder.Append(char.ToLowerInvariant(character));
                needsSeparator = false;
            }
            else
            {
                needsSeparator = true;
            }
        }

        return builder.Length == 0 ? "members" : builder.ToString();
    }

    internal static string Escape(string? value)
    {
        if (string.IsNullOrEmpty(value))
            return string.Empty;

        return value.Replace("&", "&amp;")
            .Replace("<", "&lt;")
            .Replace(">", "&gt;")
            .Replace("\"", "&quot;");
    }

    private static void WriteResource(
        string outputDirectory,
        string resourceName,
        string fileName)
    {
        using var stream = typeof(RavenDocSiteTemplate).Assembly
            .GetManifestResourceStream(resourceName)
            ?? throw new InvalidOperationException(
                $"The RavenDoc resource '{resourceName}' is missing.");
        using var reader = new StreamReader(stream);
        File.WriteAllText(Path.Combine(outputDirectory, fileName), reader.ReadToEnd());
    }
}

internal sealed record RavenDocPageTemplateModel(
    string Title,
    string Context,
    string AssemblyName,
    string HomeHref,
    string ThemeHref,
    string StyleHref,
    string ScriptHref,
    string BodyHtml,
    IReadOnlyList<DocumentationSiteLink> SiteLinks);

internal sealed record RavenDocMemberTemplateModel(
    RavenDocSymbolKind Kind,
    string Signature,
    string Href,
    string Summary);

internal sealed record RavenDocCaseTemplateModel(
    string Signature,
    string Summary);

internal enum RavenDocSymbolKind
{
    Namespace,
    Type,
    Function,
    Macro,
    Case,
    Property,
    Field,
    Event,
    Operator,
    Member
}
